### ISSUE TITLE
Can't bind to 'items' since it isn't a known property of 'data-table'

### ISSUE THREAD

**Issue by AbQayyum** [brunano21/angular-4-data-table#13]
Exception details
Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'data-table'.
1. If 'data-table' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<data-table
[ERROR ->][items]="items"
[itemCount]="itemCount" 
(reload)="reloadItems($event)"
"): ng:///AppModule/ApplistComponent.html@3:0
Can't bind to 'itemCount' since it isn't a known property of 'data-table'.
1. If 'data-table' is an Angular component and it has 'itemCount' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<data-table
[items]="items"
[ERROR ->][itemCount]="itemCount" 
(reload)="reloadItems($event)"
>
"): ng:///AppModule/ApplistComponent.html@4:0
Can't bind to 'property' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'property' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<data-table-column
[ERROR ->][property]="'title'"
[header]="'Title'",
[sortable]="true",
"): ng:///AppModule/ApplistComponent.html@9:0
Can't bind to 'header' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'header' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<data-table-column
[property]="'title'"
[ERROR ->][header]="'Title'",
[sortable]="true",
[resizable]="true"
"): ng:///AppModule/ApplistComponent.html@10:0
Can't bind to 'sortable' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'sortable' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
[property]="'title'"
[header]="'Title'",
[ERROR ->][sortable]="true",
[resizable]="true"
>
"): ng:///AppModule/ApplistComponent.html@11:0
Can't bind to 'resizable' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'resizable' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
[header]="'Title'",
[sortable]="true",
[ERROR ->][resizable]="true"
>
</data-table-column>
"): ng:///AppModule/ApplistComponent.html@12:0
'data-table-column' is not a known element:
1. If 'data-table-column' is an Angular component, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>

[ERROR ->]<data-table-column
[property]="'title'"
[header]="'Title'",
"): ng:///AppModule/ApplistComponent.html@8:0
'data-table' is not a known element:
1. If 'data-table' is an Angular component, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<h2>App list</h2>

[ERROR ->]<data-table
[items]="items"
[itemCount]="itemCount" 
"): ng:///AppModule/ApplistComponent.html@2:0

**my component is**
import { Component, OnInit } from '@angular/core';
import { DataTableResource } from "angular5-data-table";

@Component({
  selector: 'app-applist',
  templateUrl: './applist.component.html',
  styleUrls: ['./applist.component.css']
})
export class ApplistComponent implements OnInit {
  applist:AppList[];
  tableResource:DataTableResource<AppList>
  items:any[];
  itemCount:number;
  constructor() { 
    this.applist=[
      {title:'title 1',category:'one',users:30, createdDate:new Date()},
      {title:'title 2',category:'two',users:20,createdDate:new Date()},
      {title:'title 3',category:'two',users:20,createdDate:new Date()},
      {title:'fourth title',category:'three',users:10,createdDate:new Date()}
    ];
    this.tableResource=new DataTableResource(this.applist);
    this.tableResource.query({offset:0})
    .then(items=> this.items=items)
    this.tableResource.count().then(count=>this.itemCount=count)
  }

  reloadItems(params){
    if(!this.tableResource) return;

    this.tableResource.query(params)
    .then(items=> this.items=items)
  }
  ngOnInit() {
  }

}

export interface AppList{
  title:string
  category:string
  users:number
  createdDate:object
}

**and html is**

<data-table
[items]="items"
[itemCount]="itemCount" 
(reload)="reloadItems($event)"
>

<data-table-column
[property]="'title'"
[header]="'Title'",
[sortable]="true",
[resizable]="true"
>
</data-table-column>

</data-table>

**other details are**
Angular CLI: 1.7.0
Node: 6.10.2
OS: win32 x64

**Comment by brunano21** [comment]
Hi,
Sorry for the late reply. Did you sort it out?

**Comment by 28pankaj** [comment]
I have also the same issue, can anybody solved this???

**Comment by brunano21** [comment]
@28pankaj Can you share your code, please?

**Comment by AbQayyum** [comment]
@brunano21 I haven't solved it yet. will spare some time to figure this out.

**Comment by brunano21** [comment]
@AbQayyum Do you want to share some code?

**Comment by AbQayyum** [comment]
@brunano21 the issue was resolved when updated the node version to 7.9.0. you may close this.

**Comment by 28pankaj** [comment]
@brunano21 mine node version is 8.9.3.., you mean to say I degrade the version then it will work.

**Comment by brunano21** [comment]
@28pankaj which of version of angular are you using?

**Comment by 28pankaj** [comment]
@brunano21 "@angular/core": "^5.2.0",

**Comment by brunano21** [comment]
@28pankaj when are you getting this error?At runtime? Please share some code or screenshot, otherwise I cannot help you.

**Comment by AbQayyum** [comment]
@28pankaj  When I was facing the issue I had different node version, my `ng -v` command shows another version of node and `node -v ` command shows the other.

**Comment by fathimaburhana** [comment]
i am facing the same issue. my angular version is 6 and node version is 10.13.0
please help .
![Capture](https://user-images.githubusercontent.com/44427470/56090591-b6cb8100-5ec1-11e9-8fd4-45dfd1852837.PNG)
![Capture1](https://user-images.githubusercontent.com/44427470/56090592-b6cb8100-5ec1-11e9-90b7-62823500ce74.PNG)

@brunano21
