### ISSUE TITLE
Custom pagination limit list

### ISSUE THREAD

**Issue by vpenkov89** [brunano21/angular-4-data-table#14]
Hi, is it possible to change pagination limit list to custom list? 50, 100 and 250 too big for our project

**Comment by brunano21** [comment]
Hi,

At the moment it's not possible, but this feature could be added.

**Comment by brunano21** [comment]
I'm planning to add this feature in the next version.

**Comment by Bank5z0rSqt** [comment]
@brunano21  Any time frame for that to happen? :)

**Comment by brunano21** [comment]
Hi, I just published a newer version of the library, v.1.0.0 which includes tons of changes, like the possibility to defines your own `pageLimits`. Have a read of the docs, please.
