### ISSUE TITLE
Module not found error?

### ISSUE THREAD

**Issue by Hepallucion** [brunano21/angular-4-data-table#18]
Most Likely this is an angular-newb type of issue, but I stared using angular5-data-tables to replace angular-2-data-tables when I was upgrading my project to angular5. This is the next error I'm encountering. Any help you can give would be great.

```
ERROR in ./~/angular5-data-table/bundles/angular5-data-table.umd.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../Observable in C:\<Snip>\node_modules\angular5-data-table\bundles
 @ ./~/angular5-data-table/bundles/angular5-data-table.umd.js 7:19-46 11:21-48

ERROR in ./~/angular5-data-table/bundles/angular5-data-table.umd.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../operator/debounceTime in C:\<Snip>\node_modules\angular5-data-table\bundles
 @ ./~/angular5-data-table/bundles/angular5-data-table.umd.js 8:21-59

ERROR in ./~/angular5-data-table/bundles/angular5-data-table.umd.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../operator/do in C:\<Snip>\node_modules\angular5-data-table\bundles
 @ ./~/angular5-data-table/bundles/angular5-data-table.umd.js 12:11-39
```

**Comment by Christoffleroux** [comment]
Also getting this issue using angular 5.2.1 rxjs 5.5.1

**Comment by Christoffleroux** [comment]
@Hepallucion have you found solution/workaround to the issue?

**Comment by Hepallucion** [comment]
Nope, I've not found the fix yet. The issue is probably in webpack. What version of webpack are you using?

**Comment by Christoffleroux** [comment]
Hi Not using web pack, yet.... just referecing the bundle as is.

**Comment by Hepallucion** [comment]
Ive not been able to find the solution yet. What did you end up doing Christoffleroux?

**Comment by Christoffleroux** [comment]
@Hepallucion @brunano21  Nope haven't found a workaround

**Comment by brunano21** [comment]
Hi, I just published a newer version of the library, v.1.0.0 which includes tons of changes. Could you try and see if this version fixes your issue?

**Comment by Christoffleroux** [comment]
HI @brunano21 @Hepallucion 

The update did resolve this issues.

**Comment by brunano21** [comment]
Awesome 👍
