### ISSUE TITLE
How to Use this?

### ISSUE THREAD

**Issue by lenichols** [brunano21/angular-4-data-table#19]
I need to add sort and pagination functionality to my tables. I've installed the lib but how do i apply it to my tables?

**Comment by brunano21** [comment]
Hi, do you want to add server-side pagination/sorting or client-side's?

**Comment by ferprez** [comment]
Hi @brunano21, I need to implement server side pagination/sorting. How can I do it with your library ?

**Comment by brunano21** [comment]
Hi @ferprez, I was about to write an example, but then I remember about this sample code which implements what you are asking.
Please refer to [this](https://github.com/ggmod/angular-2-data-table-demo/blob/master/app/demo1/data-table-demo1-remote-service.ts) to understand how you can implement server-side pagination and/or sorting.
