### ISSUE TITLE
Setting custom [limit] makes limit select box default to empty

### ISSUE THREAD

**Issue by esiva** [brunano21/angular-4-data-table#21]
if I set [limit]="5" then the limit select box at the bottom defaulted to empty, however it has values like 10, 25, 50, 100 and 250. It would be nice if the value set in [limit] is included in the limit select box and selected as default value

![screenshot from 2018-04-24 16-44-43](https://user-images.githubusercontent.com/15943994/39183959-661947a0-47df-11e8-933e-1bda07199821.png)

**Comment by brunano21** [comment]
Hi, I'm planning this feature in the next release...I hope before the end of this week.

**Comment by brunano21** [comment]
Hi. I have fixed this within last release, v.1.0.0. Can you try it again, please? 

I have also added a proper documentation. Please, have a read. Thank you.

**Comment by esiva** [comment]
Awesome! It works nicely. Thanks.
