### ISSUE TITLE
Can't bind to 'pagination_limit' since it isn't a known property of 'data-table

### ISSUE THREAD

**Issue by KumailHussain** [brunano21/angular-4-data-table#22]
1. If 'data-table' is an Angular component and it has 'pagination_limit' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <data-table id="persons-grid"
              headerTitle="Employees"
              [ERROR ->][pagination_limit]="true"
              [items]="items"
              [itemCount]="itemCount"
"): ng:///AppModule/AppComponent.html@3:14
Can't bind to 'items' since it isn't a known property of 'data-table'.
1. If 'data-table' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
              headerTitle="Employees"
              [pagination_limit]="true"
              [ERROR ->][items]="items"
              [itemCount]="itemCount"
              (reload)="reloadItems($event)"
"): ng:///AppModule/AppComponent.html@4:14
Can't bind to 'itemCount' since it isn't a known property of 'data-table'.
1. If 'data-table' is an Angular component and it has 'itemCount' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by brunano21** [comment]
Hi, I just published a newer version of the library, v.1.0.0 which includes tons of changes. Could you try and see if this version fixes your issue?
