### ISSUE TITLE
Bootstrap 4 Styling

### ISSUE THREAD

**Issue by Christoffleroux** [brunano21/angular-4-data-table#26]
Is it posible to get the table's header to be rendered using the default bootstrap styles (No Dark Headers).

In BS the table headers are styled accorginly
![image](https://user-images.githubusercontent.com/14099247/39703354-1aef640c-5208-11e8-97e2-1102b1ac19de.png)

**Comment by brunano21** [comment]
Ops, my bad, I'll fix that soon.

**Comment by angchoo** [comment]
is it fixes??

**Comment by brunano21** [comment]
@angchoo not yet - I'll fix this early next week.

**Comment by angchoo** [comment]
thanks a lot. please let me know when it is done.

**Comment by brunano21** [comment]
Fixed with 948959a25ae8c38533b24be72dc4d13c571a13f8.
