### ISSUE TITLE
Error with prod build

### ISSUE THREAD

**Issue by codegagan** [brunano21/angular-4-data-table#27]
My [application](https://github.com/codegagan/oshop) runs fine with `ng serve` but failing with --prod build:

> ERROR in node_modules\angular5-data-table\angular5-data-table.d.ts.DataTablePagination.html(3,11): : Argument of type 'number | "0"' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.
>   Type 'number' is not assignable to type '(substring: string, ...args: any[]) => string'.

**Comment by brunano21** [comment]
@codegagan, ops, I'll fix that, unless you want submit a PR. :-)

**Comment by codegagan** [comment]
@brunano21 , I already submitted two PRs referenced above. Please accept whichever you like.

**Comment by codegagan** [comment]
Also please update the library to npm asap, My application is blocked on aot buiilds because of this.
Thanks

**Comment by codegagan** [comment]
When do you plan to review the PR, please let me know if any changes are required ?
