### ISSUE TITLE
ng build --prod Error in angular5-data-table.d.ts.DataTablePagination

### ISSUE THREAD

**Issue by jeanDenison** [brunano21/angular-4-data-table#32]
`ERROR in node_modules/angular5-data-table/angular5-data-table.d.ts.DataTablePagination.html(3,11): : Argument of type 'number | "0"' is not assignable to parameter of type '(substring: string, ...args: any[]) => string'.
  Type 'number' is not assignable to type '(substring: string, ...args: any[]) => string'.
`

**Comment by brunano21** [comment]
@jeanDenison which lib version are you using? This should be fixed already into `v1.0.1`.
