### ISSUE TITLE
Font awesome v 5.0.0 and up not supported on sorting icons

### ISSUE THREAD

**Issue by smitfrancois** [brunano21/angular-4-data-table#34]
Hi 

We are facing issues with icons not displaying from font awesome v 5.0.0.0. 

When I look at the html after the code has rendered I see the following: 
![image](https://user-images.githubusercontent.com/13797668/40776378-dd849eea-64ca-11e8-81a4-7bf1f01786b8.png)

but the icon class name has changed to 
<i class="fas fa-sort-up"></i>
<i class="fas fa-sort-down"></i>

Please advise?

Regards

**Comment by brunano21** [comment]
Hi,
the library supports only font-awesome v4.x 

Unfortunately `sort-desc` was renamed to `sort-down` in v.5.x.

**Comment by smitfrancois** [comment]
Yeah thanks. I only saw on your readme file after I logged the issue. Found a work around. Thanks. Will there be any plans in future to implement support for V.5.x?
