### ISSUE TITLE
Header buttons can't be resized or customized

### ISSUE THREAD

**Issue by dpadula** [brunano21/angular-4-data-table#37]
Is there any way to modify the header buttons? I need to separate 
the reload button from the column selector. 

![sin titulo](https://user-images.githubusercontent.com/18007723/42359315-7ef1e7e4-80b7-11e8-8602-2d646b12f0a7.png)

I'm using the angular5-data-table npm package by the way.
All the bootstrap (and other) styles I've tried in my component.css file did not worked.

Thanks in advance.

Cheers

**Comment by brunano21** [comment]
@dpadula are you still interested in this? or did you find out a solution?

**Comment by dpadula** [comment]
I'm sorry yes! I've found the solution. That was a bit weird because I didn't know this css form to access the styles of component.

:host /deep/ .nameOfTheClassToModify

Thanks anyway
