### ISSUE TITLE
Drag and drop column and grouping is available for angular-4-data-table?

### ISSUE THREAD

**Issue by prakashkaruppiah** [brunano21/angular-4-data-table#38]
Drag and drop column and grouping is available for angular-4-data-table?

**Comment by brunano21** [comment]
Unfortunately, these features are missing.

**Comment by prakashkaruppiah** [comment]
Do you have any idea to implement this feature in future?

**Comment by brunano21** [comment]
Hi @prakashkaruppiah. Unfortunately no plans for this feature in the short term. But I'm open for pull requests!

**Comment by prakashkaruppiah** [comment]
Thanks for your response.
