### ISSUE TITLE
How to create dynamic column?

### ISSUE THREAD

**Issue by prakashkaruppiah** [brunano21/angular-4-data-table#40]
Hi @brunano21 ,
How to create dynamic column in angular-4-data-table?. Please help us.

**Comment by brunano21** [comment]
what do you mean by creating dynamic columns?

**Comment by prakashkaruppiah** [comment]
Hi @brunano21 ,
We need 
data-table-column
dynamically for example we pass data set to Items property [items]="dataset",
First time columns  will  come : Col1,Col2,Col3
Second time columns will come  : Col1,Col2,Col3,Col4,Col5
In this scenario i tried *ng for for data column dynamically generation but its not working.
Please give me any suggestion.

**Comment by brunano21** [comment]
All columns have to be defined into your component's template. However, you can toggle its visibility using the `visible` flag. Would it be helpful?
