### ISSUE TITLE
possibility to show or hide header button and pagination server side

### ISSUE THREAD

**Issue by cfasol** [brunano21/angular-4-data-table#41]
possibility to show or hide
possibility to mange pagination server side
thanks

**Comment by brunano21** [comment]
???

**Comment by brunano21** [comment]
@cfasol do you have any progress on this?

**Comment by cfasol** [comment]
Hi, yes I forked your project and I added 2 properties to manage buttons's
visibility( showReloadButton and showColumnSelectorButton ) I undestood how
to manage server side operations

Sorry, but are you italian?

thanks regards

Saluti
Fasolin Cristopher

<http://www.destinazioneinformatica.com/>


Il giorno ven 3 ago 2018 alle ore 10:53 Bruno Bruzzano <
notifications@github.com> ha scritto:

**Comment by brunano21** [comment]
Cool, if you don't mind, you can create a PR too. And yes, I'm Italian :-)

**Comment by cfasol** [comment]
Great, I am italian too... thanks
Ciao e buona serata.

Il ven 3 ago 2018, 20:50 Bruno Bruzzano <notifications@github.com> ha
scritto:
