### ISSUE TITLE
How to show sum of amount in data table column footer?

### ISSUE THREAD

**Issue by prakashkaruppiah** [brunano21/angular-4-data-table#42]
How to show sum of amount in data table column footer? Is this possible ? Please help us.

**Comment by prakashkaruppiah** [comment]
Hi @brunano21 , 
Any updates?

**Comment by brunano21** [comment]
What do you mean by sum of amount? Amount of what?
Also, it doesn't exist any _data table column footer_.

**Comment by prakashkaruppiah** [comment]
hi @brunano21 ,
I mean column aggregate(SUM,AVG, etc) function

Please see this link (column name :price )  footer total amount :
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/customaggregates.htm?arctic

**Comment by brunano21** [comment]
Hi,
No it's not natively supported. However you could manipulate the table data and obtain the same result.

**Comment by prakashkaruppiah** [comment]
OK Thanks we will check.
