### ISSUE TITLE
How about coloring by column via dataTableCell?

### ISSUE THREAD

**Issue by dpadula** [brunano21/angular-4-data-table#44]
Is this possible?
In this page https://ggmod.github.io/angular-2-data-table-demo/ the example #3 have a column colored by a function:

        <data-table-column
            [property]="'rating'"
            [header]="'Rating'"
            [sortable]="true"
            [cellColors]="cellColor">
        </data-table-column>

Where the function in the .ts file is:

    cellColor(car) {
        return 'rgb(255, 255,' + (155 + Math.floor(100 - ((car.rating - 8.7)/1.3)*100)) + ')';
    };

Thanks!

**Comment by dpadula** [comment]
Is this the correct way?

:host /deep/ .data-column.column-nameColumn {
    background-color: #ffaaff;
}

**Comment by brunano21** [comment]
yes, you can colour a specific cell. If you download the entire repo and put the demo up and running, you can see various examples.

Also, you can use both ways of applying cell colour.

**Comment by dpadula** [comment]
Genius, thanks! I really appreciate this.
