### ISSUE TITLE
How to set default sorting column

### ISSUE THREAD

**Issue by carlosmori94** [brunano21/angular-4-data-table#51]
I want my grid to start with the arrow facing up so the user knows the grid is sorted by default.
![image](https://user-images.githubusercontent.com/21184028/44931879-8885a080-ad39-11e8-9257-cbe216e55a1d.png)

Thanks in advance!

**Comment by brunano21** [comment]
Hi, you can use DataTable's`[sortAsc]=true`.

**Comment by carlosmori94** [comment]
@brunano21 Thanks for the fast reply but that isn't working, when I populating the grid I need the first column to start with an intuitive arrow facing up, so the user understands is sorted by default.
I got it like this
![image](https://user-images.githubusercontent.com/21184028/44934355-e8cd1000-ad42-11e8-81d3-37b5bd0b51ae.png)

I need it like this
![image](https://user-images.githubusercontent.com/21184028/44934322-d226b900-ad42-11e8-9856-ed8e3ffdb556.png)

**Comment by brunano21** [comment]
Hi, then you also need to set `[sortBy]="'policyNumber'"`. This will sort the table by _Policy #_.

**Comment by carlosmori94** [comment]
Thanks man, that worked perfectly!
