### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by DinukaGayan** [brunano21/angular-4-data-table#9]
Can you describe how to implement filter function in this?Column wise searching and All columns

**Comment by brunano21** [comment]
You can rewrite the `reloadTable` function as the following, passing a second arg to the `query` function:
```
carResource = new DataTableResource(cars);

reloadTable() {
    this.carResource .query(params, **filterFunc**).then(cars => this.cars = cars);`
}

```
filterFunc signature is `(item: T, index: number, items: T[]) => boolean)`
